---
- hosts: masters[0]
  gather_facts: False
  vars:
    network_role: network_multus
  # unset http_proxy. required for running in the CI
  environment:
    http_proxy: ""
  roles:
  - { role: "network-multus", when: network_role == 'network-multus'}
